trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: CI
  displayName: 'Build e Testes'
  jobs:
  - job: BuildTest
    displayName: 'Maven Build + Testes unitarios'
    steps:
    - task: Maven@4
      displayName: 'mvn package'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        options: '-DskipTests=false'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
    - task: PublishBuildArtifacts@1
      displayName: 'Publicar JAR'
      inputs:
        pathToPublish: 'target'
        artifactName: 'backend-jar'

- stage: CD
  displayName: 'Deploy Azure App Service'
  dependsOn: CI
  jobs:
  - deployment: DeployBackend
    displayName: 'Deploy para producao'
    environment: 'producao'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy JAR no Azure App Service'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appType: 'webAppLinux'
              appName: 'nutryon-f8h2e8bqa0d7gjbx'
              package: '$(Pipeline.Workspace)/backend-jar/*.jar'
