-- =============================================================
-- Nutryon — DDL Completo (Oracle Autonomous Database / Oracle Cloud)
-- Equipe DimDim: Renato (RM560928), Victor (RM560087),
--                Luan Noqueli Klochko (RM560313),
--                Lucas Higuti Fontanezi (RM561120)
-- =============================================================
-- Este arquivo representa a estrutura final do banco de dados
-- após a execução de todas as migrations Flyway (V1 a V4).
-- Para deploy em nuvem: execute no Oracle Cloud Autonomous Database.
-- Para desenvolvimento: o Flyway aplica automaticamente ao subir o backend.
-- =============================================================

--------------------------------------------------------
-- 0) LIMPEZA (executar apenas se necessário recriar do zero)
--    ATENÇÃO: apaga todos os dados existentes
--------------------------------------------------------
-- BEGIN
--   FOR t IN (SELECT table_name FROM user_tables
--             WHERE table_name NOT IN ('FLYWAY_SCHEMA_HISTORY')) LOOP
--     BEGIN
--       EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS PURGE';
--     EXCEPTION WHEN OTHERS THEN NULL;
--     END;
--   END LOOP;
-- END;
-- /

--------------------------------------------------------
-- 1) TABELA: USUARIOS
--------------------------------------------------------
CREATE TABLE usuarios (
  id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nome   VARCHAR2(100)  NOT NULL,
  email  VARCHAR2(120)  NOT NULL,
  senha  VARCHAR2(255)  NOT NULL,
  role   VARCHAR2(40)   NOT NULL,
  CONSTRAINT PK_USUARIO        PRIMARY KEY (id),
  CONSTRAINT UK_USUARIO_EMAIL  UNIQUE (email),
  CONSTRAINT CK_USUARIO_EMAIL_REGEX
    CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
);

--------------------------------------------------------
-- 2) TABELA: INGREDIENTES
--------------------------------------------------------
CREATE TABLE ingredientes (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nome            VARCHAR2(120)  NOT NULL,
  unidade_base    VARCHAR2(20)   NOT NULL,
  kcal_por100     NUMBER(12,3)   NOT NULL,
  proteina_por100 NUMBER(12,3)   NOT NULL,
  carbo_por100    NUMBER(12,3)   NOT NULL,
  gordura_por100  NUMBER(12,3)   NOT NULL,
  CONSTRAINT PK_INGREDIENTE       PRIMARY KEY (id),
  CONSTRAINT UK_INGREDIENTE_NOME  UNIQUE (nome)
);

--------------------------------------------------------
-- 3) TABELA: REFEICOES
--    Relacionamento N:1 com USUARIOS
--    Unique: um usuário não pode ter dois registros do mesmo tipo no mesmo dia
--------------------------------------------------------
CREATE TABLE refeicoes (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  usuario_id  NUMBER        NOT NULL,
  data        DATE          NOT NULL,
  tipo        VARCHAR2(40)  NOT NULL,
  CONSTRAINT PK_REFEICAO            PRIMARY KEY (id),
  CONSTRAINT FK_REF_USR             FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
  CONSTRAINT UK_REF_USR_DATA_TIPO   UNIQUE (usuario_id, data, tipo)
);

--------------------------------------------------------
-- 4) TABELA: ITENS_REFEICAO
--    Relacionamento N:1 com REFEICOES e N:1 com INGREDIENTES
--    Armazena a quantidade consumida do ingrediente na refeição
--------------------------------------------------------
CREATE TABLE itens_refeicao (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
  refeicao_id     NUMBER        NOT NULL,
  ingrediente_id  NUMBER        NOT NULL,
  quantidade      NUMBER(12,3)  NOT NULL,
  CONSTRAINT PK_ITEM_REFEICAO  PRIMARY KEY (id),
  CONSTRAINT FK_RI_REF         FOREIGN KEY (refeicao_id)    REFERENCES refeicoes(id),
  CONSTRAINT FK_RI_ING         FOREIGN KEY (ingrediente_id) REFERENCES ingredientes(id)
);

--------------------------------------------------------
-- 5) ÍNDICES DE PERFORMANCE
--------------------------------------------------------
CREATE INDEX IX_REF_USR_DT ON refeicoes (usuario_id, data);
CREATE INDEX IX_RI_ING     ON itens_refeicao (ingrediente_id);

--------------------------------------------------------
-- 6) TRIGGERS DE NORMALIZAÇÃO
--    Garante padronização dos dados sem depender do cliente
--------------------------------------------------------

-- Normaliza nome do usuário para MAIÚSCULAS e email para minúsculas
CREATE OR REPLACE TRIGGER TRG_USUARIO_BIU
BEFORE INSERT OR UPDATE ON usuarios
FOR EACH ROW
BEGIN
  :NEW.nome  := UPPER(TRIM(:NEW.nome));
  :NEW.email := LOWER(TRIM(:NEW.email));
END;
/

-- Normaliza nome do ingrediente para MAIÚSCULAS
CREATE OR REPLACE TRIGGER TRG_INGREDIENTE_BIU
BEFORE INSERT OR UPDATE ON ingredientes
FOR EACH ROW
BEGIN
  :NEW.nome := UPPER(TRIM(:NEW.nome));
END;
/

--------------------------------------------------------
-- 7) SEED — Dados iniciais obrigatórios
--    Usuário ADMIN padrão (senha: 123456 com BCrypt)
--    Ingredientes base para demonstração
--------------------------------------------------------

-- Usuário administrador padrão
-- Credenciais de login: admin@nutryon.com / 123456
INSERT INTO usuarios (nome, email, senha, role)
VALUES (
  'Administrador',
  'admin@nutryon.com',
  '$2a$10$GSg85ob6JxkP48G8WT8OUuOVz9h04tSxFKEtYkY7PznXvTDgTKFRa',
  'ADMIN'
);

-- Ingredientes base
INSERT INTO ingredientes (nome, unidade_base, kcal_por100, proteina_por100, carbo_por100, gordura_por100)
VALUES ('ARROZ BRANCO COZIDO', 'GRAMA', 130.000, 2.500, 28.000, 0.200);

INSERT INTO ingredientes (nome, unidade_base, kcal_por100, proteina_por100, carbo_por100, gordura_por100)
VALUES ('PEITO DE FRANGO GRELHADO', 'GRAMA', 165.000, 31.000, 0.000, 3.600);

INSERT INTO ingredientes (nome, unidade_base, kcal_por100, proteina_por100, carbo_por100, gordura_por100)
VALUES ('OVO COZIDO', 'UNID', 155.000, 13.000, 1.100, 11.000);

COMMIT;

-- =============================================================
-- RELACIONAMENTOS — RESUMO
-- =============================================================
-- usuarios (1) ──────────────── (N) refeicoes
-- refeicoes (1) ─────────────── (N) itens_refeicao
-- ingredientes (1) ──────────── (N) itens_refeicao
-- =============================================================
-- VALORES VÁLIDOS
-- =============================================================
-- usuarios.role       → 'ADMIN' | 'USER'
-- refeicoes.tipo      → 'CAFE' | 'ALMOCO' | 'LANCHE' | 'JANTAR'
-- ingredientes.unidade_base → 'GRAMA' | 'KILOGRAMA' | 'LITRO' | 'ML' | 'UNID'
-- =============================================================
