--------------------------------------------------------
-- V1: Schema inicial - tabelas de usuários e ingredientes
--------------------------------------------------------

CREATE TABLE usuarios (
  id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nome  VARCHAR2(100) NOT NULL,
  email VARCHAR2(120) NOT NULL,
  CONSTRAINT PK_USUARIO_V1   PRIMARY KEY (id),
  CONSTRAINT UK_USUARIO_EMAIL_V1 UNIQUE (email)
);

CREATE TABLE ingredientes (
  id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR2(120) NOT NULL,
  CONSTRAINT PK_INGREDIENTE_V1   PRIMARY KEY (id),
  CONSTRAINT UK_INGREDIENTE_NOME_V1 UNIQUE (nome)
);
