--------------------------------------------------------
-- V2: Sprint 1 - autenticação e dados nutricionais
--------------------------------------------------------

ALTER TABLE usuarios ADD (
  senha VARCHAR2(255) DEFAULT 'pendente' NOT NULL,
  role  VARCHAR2(40)  DEFAULT 'USER'     NOT NULL
);

ALTER TABLE ingredientes ADD (
  unidade_base    VARCHAR2(20)  DEFAULT 'G' NOT NULL,
  kcal_por100     NUMBER(12,3)  DEFAULT 0   NOT NULL,
  proteina_por100 NUMBER(12,3)  DEFAULT 0   NOT NULL,
  carbo_por100    NUMBER(12,3)  DEFAULT 0   NOT NULL,
  gordura_por100  NUMBER(12,3)  DEFAULT 0   NOT NULL
);

CREATE TABLE refeicoes (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
  usuario_id NUMBER NOT NULL,
  data       DATE   NOT NULL,
  tipo       VARCHAR2(40) NOT NULL,
  CONSTRAINT PK_REFEICAO_V2 PRIMARY KEY (id),
  CONSTRAINT FK_REF_USR_V2  FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
