--------------------------------------------------------
-- V3: Sprint 2 - itens de refeição e índices de desempenho
--------------------------------------------------------

CREATE TABLE itens_refeicao (
  id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
  refeicao_id    NUMBER        NOT NULL,
  ingrediente_id NUMBER        NOT NULL,
  quantidade     NUMBER(12,3)  NOT NULL,
  CONSTRAINT PK_ITEM_REFEICAO_V3 PRIMARY KEY (id),
  CONSTRAINT FK_RI_REF_V3 FOREIGN KEY (refeicao_id)    REFERENCES refeicoes(id),
  CONSTRAINT FK_RI_ING_V3 FOREIGN KEY (ingrediente_id) REFERENCES ingredientes(id)
);

CREATE INDEX IX_REF_USR_DT_V3 ON refeicoes      (usuario_id, data);
CREATE INDEX IX_RI_ING_V3     ON itens_refeicao (ingrediente_id);
