--------------------------------------------------------
-- 0) LIMPEZA DO ESQUEMA ANTIGO (EXCETO FLYWAY)
--------------------------------------------------------
BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name != 'FLYWAY_SCHEMA_HISTORY') LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE "'||t.table_name||'" CASCADE CONSTRAINTS PURGE';
    EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;
END;
/

--------------------------------------------------------
-- 1) TABELAS BÁSICAS
--------------------------------------------------------

-- USUARIOS
CREATE TABLE usuarios (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR2(100) NOT NULL,
  email VARCHAR2(120) NOT NULL,
  senha VARCHAR2(255) NOT NULL,
  role VARCHAR2(40) NOT NULL,
  CONSTRAINT PK_USUARIO PRIMARY KEY (id),
  CONSTRAINT UK_USUARIO_EMAIL UNIQUE (email),
  CONSTRAINT CK_USUARIO_EMAIL_REGEX CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
);

-- INGREDIENTES
CREATE TABLE ingredientes (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR2(120) NOT NULL,
  unidade_base VARCHAR2(20) NOT NULL,
  kcal_por100 NUMBER(12,3) NOT NULL,
  proteina_por100 NUMBER(12,3) NOT NULL,
  carbo_por100 NUMBER(12,3) NOT NULL,
  gordura_por100 NUMBER(12,3) NOT NULL,
  CONSTRAINT PK_INGREDIENTE PRIMARY KEY (id),
  CONSTRAINT UK_INGREDIENTE_NOME UNIQUE (nome)
);

-- REFEICOES
CREATE TABLE refeicoes (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  usuario_id NUMBER NOT NULL,
  data DATE NOT NULL, 
  tipo VARCHAR2(40) NOT NULL,
  CONSTRAINT PK_REFEICAO PRIMARY KEY (id),
  CONSTRAINT FK_REF_USR FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
  CONSTRAINT UK_REF_USR_DATA_TIPO UNIQUE (usuario_id, data, tipo)
);

-- ITENS_REFEICAO
CREATE TABLE itens_refeicao (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  refeicao_id NUMBER NOT NULL,
  ingrediente_id NUMBER NOT NULL,
  quantidade NUMBER(12,3) NOT NULL,
  CONSTRAINT PK_ITEM_REFEICAO PRIMARY KEY (id),
  CONSTRAINT FK_RI_REF FOREIGN KEY (refeicao_id) REFERENCES refeicoes(id),
  CONSTRAINT FK_RI_ING FOREIGN KEY (ingrediente_id) REFERENCES ingredientes(id)
);

--------------------------------------------------------
-- 2) ÍNDICES E TRIGGERS DE NORMALIZAÇÃO
--------------------------------------------------------
CREATE INDEX IX_REF_USR_DT ON refeicoes (usuario_id, data);
CREATE INDEX IX_RI_ING ON itens_refeicao (ingrediente_id);

-- USUARIO: normaliza nome
CREATE OR REPLACE TRIGGER TRG_USUARIO_BIU
BEFORE INSERT OR UPDATE ON usuarios
FOR EACH ROW
BEGIN
  :NEW.nome := UPPER(TRIM(:NEW.nome));
  :NEW.email := LOWER(TRIM(:NEW.email));
END;
/

-- INGREDIENTE: normaliza nome
CREATE OR REPLACE TRIGGER TRG_INGREDIENTE_BIU
BEFORE INSERT OR UPDATE ON ingredientes
FOR EACH ROW
BEGIN
  :NEW.nome := UPPER(TRIM(:NEW.nome));
END;
/

--------------------------------------------------------
-- 3) SEED BÁSICO (Opcional - usuário ADMIN padrão)
--------------------------------------------------------
-- Senha é '123456' hasheada com Bcrypt (gerada pelo Spring Security)
INSERT INTO usuarios (nome, email, senha, role) 
VALUES ('Administrador', 'admin@nutryon.com', '$2a$10$fWnJ8t9/mP83Pob88G.sEOGU/nZkY5f0dON/lH4x5yH/.Q8lJ4uR2', 'ADMIN');

INSERT INTO ingredientes (nome, unidade_base, kcal_por100, proteina_por100, carbo_por100, gordura_por100) 
VALUES ('ARROZ BRANCO COZIDO', 'G', 130.00, 2.50, 28.00, 0.20);

INSERT INTO ingredientes (nome, unidade_base, kcal_por100, proteina_por100, carbo_por100, gordura_por100) 
VALUES ('PEITO DE FRANGO GRELHADO', 'G', 165.00, 31.00, 0.00, 3.60);

INSERT INTO ingredientes (nome, unidade_base, kcal_por100, proteina_por100, carbo_por100, gordura_por100) 
VALUES ('OVO COZIDO', 'UNID', 155.00, 13.00, 1.10, 11.00);

COMMIT;
